version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_training_psql
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: