-- Создание таблицы book
-- CREATE TABLE book (
--   book_id int NOT NULL,
--   title varchar(50) NOT NULL,
--   author varchar(30) NOT NULL,
--   price decimal(8,2) NOT NULL,
--   amount int NOT NULL
-- );

-- INSERT INTO book (book_id, title, author, price, amount) VALUES
-- (1, 'Мастер и Маргарита', 'Булгаков М.А.', '670.99', 3),
-- (2, 'Белая гвардия', 'Булгаков М.А.', '540.50', 5),
-- (3, 'Идиот', 'Достоевский Ф.М.', '460.00', 10),
-- (4, 'Братья Карамазовы', 'Достоевский Ф.М.', '799.01', 3),
-- (5, 'Игрок', 'Достоевский Ф.М.', '480.50', 10),
-- (6, 'Стихотворения и поэмы', 'Есенин С.А.', '650.00', 15);